import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
export const ReportsPage = ({ reports, onCloseCase }) => {
    const [totalResponseSeconds, setTotalResponseSeconds] = useState("420");
    const [ambulanceArrivalSeconds, setAmbulanceArrivalSeconds] = useState("190");
    const [volunteerArrivalSeconds, setVolunteerArrivalSeconds] = useState("140");
    const [interventions, setInterventions] = useState("Guided airway support, bleeding control, oxygen prep.");
    const [notes, setNotes] = useState("Volunteer stabilized patient before ambulance handover.");
    const [outcome, setOutcome] = useState("Resolved after first aid and ambulance handover");
    return (_jsxs("section", { className: "page-stack", children: [_jsxs("article", { className: "panel", children: [_jsx("header", { className: "panel__header", children: _jsx("h3", { children: "Incident Closure" }) }), _jsx("label", { className: "form-label", htmlFor: "total-response-seconds", children: "Total response time (sec)" }), _jsx("input", { id: "total-response-seconds", value: totalResponseSeconds, onChange: (event) => setTotalResponseSeconds(event.target.value) }), _jsx("label", { className: "form-label", htmlFor: "ambulance-arrival-seconds", children: "Ambulance arrival time (sec)" }), _jsx("input", { id: "ambulance-arrival-seconds", value: ambulanceArrivalSeconds, onChange: (event) => setAmbulanceArrivalSeconds(event.target.value) }), _jsx("label", { className: "form-label", htmlFor: "volunteer-arrival-seconds", children: "Volunteer arrival time (sec)" }), _jsx("input", { id: "volunteer-arrival-seconds", value: volunteerArrivalSeconds, onChange: (event) => setVolunteerArrivalSeconds(event.target.value) }), _jsx("label", { className: "form-label", htmlFor: "interventions", children: "Interventions performed" }), _jsx("textarea", { id: "interventions", value: interventions, onChange: (event) => setInterventions(event.target.value) }), _jsx("label", { className: "form-label", htmlFor: "notes", children: "Dispatcher notes" }), _jsx("textarea", { id: "notes", value: notes, onChange: (event) => setNotes(event.target.value) }), _jsx("label", { className: "form-label", htmlFor: "outcome", children: "Final outcome" }), _jsx("textarea", { id: "outcome", value: outcome, onChange: (event) => setOutcome(event.target.value) }), _jsx("div", { className: "button-row", children: _jsx("button", { onClick: () => onCloseCase({
                                totalResponseSeconds: Number(totalResponseSeconds) || undefined,
                                ambulanceArrivalSeconds: Number(ambulanceArrivalSeconds) || undefined,
                                volunteerArrivalSeconds: Number(volunteerArrivalSeconds) || undefined,
                                interventions: interventions.trim() || undefined,
                                notes: notes.trim() || undefined,
                                finalOutcome: outcome.trim()
                            }), children: "Close Case" }) })] }), _jsxs("article", { className: "panel", children: [_jsx("header", { className: "panel__header", children: _jsx("h3", { children: "Reporting Summary" }) }), _jsx("div", { className: "table-wrapper", children: _jsxs("table", { className: "table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Date" }), _jsx("th", { children: "Daily Case Count" }), _jsx("th", { children: "Avg Response Time (sec)" }), _jsx("th", { children: "Volunteer Contributions" })] }) }), _jsx("tbody", { children: reports.map((item) => (_jsxs("tr", { children: [_jsx("td", { children: item.date }), _jsx("td", { children: item.caseCount }), _jsx("td", { children: item.avgTotalResponseSeconds ?? "N/A" }), _jsx("td", { children: item.volunteerContributions })] }, item.date))) })] }) })] })] }));
};
